{"name": "Try Signup With Invalid Username", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsSignup' object has no attribute 'goto'", "trace": "page = <tests.test_auth.TestsSignup object at 0x0000027B853BCFC0>\n\n    @allure.story(\"Попытка регистрации под невалидным именем пользователя\")\n    def test_try_signup_with_invalid_username(page: Page):\n>       page.goto(f\"{base_auth_url}register\")\n        ^^^^^^^^^\nE       AttributeError: 'TestsSignup' object has no attribute 'goto'\n\ntests\\test_auth.py:78: AttributeError"}, "start": 1751800039724, "stop": 1751800039725, "uuid": "ad9e4164-d8b0-4213-8439-7705ba463d74", "historyId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "testCaseId": "5bf71bf0cb3efa99e9ce6fbe2d86867e", "fullName": "tests.test_auth.TestsSignup#test_try_signup_with_invalid_username", "labels": [{"name": "feature", "value": "Регистрация"}, {"name": "story", "value": "Попытка регистрации под невалидным именем пользователя"}, {"name": "epic", "value": "Форма регистрации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsSignup"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}