{"name": "Failed Signin", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsAuth' object has no attribute 'goto'", "trace": "page = <tests.test_auth.TestsAuth object at 0x0000027B8557C7D0>\n\n    @allure.story(\"Авторизация под неверными данными\")\n    def test_failed_signin(page: Page):\n    \n        username = fake.user_name()\n        password = fake.password()\n    \n>       page.goto(f\"{base_auth_url}login\")\n        ^^^^^^^^^\nE       AttributeError: 'TestsAuth' object has no attribute 'goto'\n\ntests\\test_auth.py:37: AttributeError"}, "start": 1751800039706, "stop": 1751800039706, "uuid": "b23c3734-39b0-4f2f-bc01-e9df35cc1318", "historyId": "700ade0d555b3463802fad87e2c9707b", "testCaseId": "700ade0d555b3463802fad87e2c9707b", "fullName": "tests.test_auth.TestsAuth#test_failed_signin", "labels": [{"name": "story", "value": "Авторизация под неверными данными"}, {"name": "feature", "value": "Авторизация"}, {"name": "epic", "value": "Форма авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsAuth"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}